### ISSUE TITLE
Homepage (Banner Styling)

### ISSUE THREAD

**Issue by TomasDev63** [DMU-CTEC2902/XCode-Repo#22]
Need some opinions about what to do with this banner.

![Capture](https://user-images.githubusercontent.com/47025857/54218081-89bc3500-44f5-11e9-9e27-79d4dbd6b31c.JPG)

**Comment by robjohnson123** [comment]
![Film Review Home](https://user-images.githubusercontent.com/46783969/54523142-b691a180-4966-11e9-8549-66ef1bce99b3.png)

Preliminary sketches for the home page. These will be improved to go alongside the final submission.
